# NOTE remember to choose a rest-client environment in the bottom of VS Code
# For more info: https://marketplace.visualstudio.com/items?itemName=humao.rest-client#environments

### Navigation
@lang = sv
@userGroupId = 312
GET {{host}}/navigation?lang={{lang}}


### Guidegroup
GET {{host}}/guidegroup?lang={{lang}}&include=221,222,223,279,5080

### Guide
@guideId = 267
GET {{host}}/guide?lang={{lang}}&include={{guideId}}

### Guide
GET {{host}}/guide/{{guideId}}

### Languages
GET {{host}}/languages

@dateStart = 2020-01-22
@dateEnd = 2020-01-22
### Raw Events
GET https://api.helsingborg.se/event/json/wp/v2/event/time?group-id={{userGroupId}}&lang={{lang}}&start={{dateStart}}&end={{dateEnd}}

### Events
GET {{host}}/events?lang={{lang}}&dateStart={{dateStart}}&dateEnd={{dateEnd}}&userGroupId={{userGroupId}}

